apiVersion: v1

kind: ReplicationController

metadata:
  name: coffee-rc2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: harbor.corp.local/library/hello:1.1
        ports:
        - containerPort: 80
---
apiVersion: v1

kind: ReplicationController

metadata:
  name: tea-rc2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: harbor.corp.local/library/hello:1.1
        ports:
        - containerPort: 80
